#!/usr/bin/env python3
"""Emit only the Unicode categories used by pinned SimpleTokenizer.

Run with references/.venv-tinygrad-py311/bin/python (Unicode 14.0.0).
No normalization/case-mapping database is part of the runtime.
"""
import itertools
import unicodedata

assert unicodedata.unidata_version == '14.0.0', unicodedata.unidata_version
print('/* Generated by test/generate_tokenizer_unicode.py; Unicode 14.0.0.')
print(' * Mirrors tinygrad/llm/cli.py SimpleTokenizer.ucat_range, CPython 3.11. */')
print('#ifndef POLY_TOKENIZER_UNICODE_H\n#define POLY_TOKENIZER_UNICODE_H\n#include <stdint.h>')
for category, name in [('L', 'letters'), ('N', 'numbers'), ('Z', 'spaces')]:
    cps = enumerate(cp for cp in range(0x323b0) if unicodedata.category(chr(cp)).startswith(category))
    print(f'static const uint32_t tok_{name}[][2] = {{')
    for _, group in itertools.groupby(cps, lambda item: item[1] - item[0]):
        run = list(group)
        print(f'    {{0x{run[0][1]:x}, 0x{run[-1][1]:x}}},')
    print('};')
print('#endif')
