#include "test_harness.h"
#include "../src/models/llama.h"
#include "../src/loaders/import_desc.h"

/* Shared deterministic oracle, generated by test/generate_llama_fixture.py. */
static cJSON *llama_fixture(void) {
  FILE *f = fopen("test/fixtures/llama.json", "rb");
  if (!f) return NULL;
  char data[32768];
  size_t n = fread(data, 1, sizeof(data), f);
  bool ok = !ferror(f) && feof(f);
  fclose(f);
  return ok ? cJSON_ParseWithLength(data, n) : NULL;
}

TEST(llama, reference_logits_and_owned_state) {
  cJSON *fixture = llama_fixture();
  ASSERT_NOT_NULL(fixture);
  cJSON *cases = cJSON_GetObjectItemCaseSensitive(fixture, "cases");
  ASSERT_EQ(cJSON_GetArraySize(cases), 4);
  const PolyImportDesc *desc = poly_import_desc_find("llama");
  ASSERT_TRUE(desc && desc->from_hf_decoded);
  PolyCtx *ctx = poly_ctx_new();
  ASSERT_NOT_NULL(ctx);
  for (int c = 0; c < 5; c++) {
    cJSON *item = cJSON_GetArrayItem(cases, c < 4 ? c : 3);
    cJSON *config = cJSON_GetObjectItemCaseSensitive(item, "config");
    cJSON *weights = cJSON_GetObjectItemCaseSensitive(item, "weights");
    int n = cJSON_GetArraySize(weights), idx = 0;
    PolyDecodedTensor *ts = calloc((size_t)n, sizeof(*ts));
    ASSERT_NOT_NULL(ts);
    cJSON *weight;
    cJSON_ArrayForEach(weight, weights) {
      PolyDecodedTensor *t = &ts[idx++];
      t->name = weight->string;
      t->ndim = cJSON_GetArraySize(weight);
      t->numel = 1;
      int offset = 0;
      for (const char *p = t->name; *p; p++)
        offset += (unsigned char)*p;
      for (int d = 0; d < t->ndim; d++) {
        t->shape[d] = cJSON_GetArrayItem(weight, d)->valueint;
        t->numel *= t->shape[d];
      }
      float *data = malloc((size_t)t->numel * sizeof(float));
      ASSERT_NOT_NULL(data);
      for (int64_t j = 0; j < t->numel; j++)
        data[j] = (float)((t->ndim == 1 ? 1.0 : 0.0) + ((j * 7 + offset) % 23 - 11) * 0.017);
      t->data = data;
      t->dtype = POLY_DECODED_F32;
      /* Safetensors may retain either member of a tied embedding/head pair. */
      if (c == 4 && !strcmp(t->name, "model.embed_tokens.weight")) t->name = "lm_head.weight";
    }
    PolyHfDecoded hf = {.config = config, .model_type = "llama", .tensors = ts, .n_tensors = n};
    PolyGenericImportOpts opts = {.ctx = ctx, .max_batch = 1, .max_seq_len = 3};
    PolyModel *m = desc->from_hf_decoded(&hf, &opts);
    for (int i = 0; i < n; i++)
      free((void *)ts[i].data);
    free(ts);
    ASSERT_NOT_NULL(m);
    int32_t tokens[] = {1, 4, 2};
    PolyIOBinding io = POLY_IO_BINDING_ARRAY("tokens", tokens, POLY_INT32);
    ASSERT_EQ(poly_model_call(m, "forward", &io, 1), 0);
    float values[33];
    ASSERT_EQ(poly_model_read_buf_named(m, "logits", values, sizeof(values)), 0);
    cJSON *expected = cJSON_GetObjectItemCaseSensitive(item, "logits");
    for (int j = 0; j < 33; j++)
      ASSERT_FLOAT_EQ(values[j], cJSON_GetArrayItem(expected, j)->valuedouble, 2e-5);
    poly_model_free(m);
    poly_ctx_collect(ctx);
  }
  poly_ctx_destroy(ctx);
  cJSON_Delete(fixture);
  PASS();
}

TEST(llama, malformed_config_preserves_context) {
  PolyCtx *ctx = poly_ctx_new();
  PolyLogicalPolicy policy = poly_ctx_get_logical_policy(ctx);
  const char *inputs[] = {"{}", "[]", "null", "{} false", "{\"hidden_size\":1.5}"};
  for (int i = 0; i < 5; i++) {
    PolyModelError err = {0};
    PolyModel *m = poly_llama_from_json(ctx, inputs[i], (int)strlen(inputs[i]), &err);
    ASSERT_TRUE(!m && err.message[0]);
    ASSERT_EQ(poly_ctx_get_logical_policy(ctx), policy);
  }
  poly_ctx_destroy(ctx);
  PASS();
}

TEST(llama, rejected_bias_reports_invalid_status) {
  PolyCtx *ctx = poly_ctx_new();
  const char *json[] = {"{\"attention_bias\":true}", "{\"mlp_bias\":true}"};
  int codes[2];
  bool rejected[2];
  for (int i = 0; i < 2; i++) {
    PolyModelError err = {0};
    PolyModel *m = poly_llama_from_json(ctx, json[i], (int)strlen(json[i]), &err);
    codes[i] = err.code;
    rejected[i] = !m && strstr(err.message, "must be false");
    poly_model_free(m);
  }
  poly_ctx_destroy(ctx);
  for (int i = 0; i < 2; i++) {
    ASSERT_TRUE(rejected[i]);
    ASSERT_INT_EQ(codes[i], POLY_STATUS_INVALID);
  }
  PASS();
}
